version: '3'

services:
#  localstack:
#    image: localstack/localstack
#    ports:
#      - "443:443"
#      - "4567-4599:4567-4599"
#      - "8080:8080"
#    environment:
#      - LOCALSTACK_API_KEY=bSEhjitgiV
#      - DEBUG=1
#      - DATA_DIR=/tmp/localstack/data
#      - PORT_WEB_UI=8080
#      - DOCKER_HOST=unix:///var/run/docker.sock
#    volumes:
#      - "/tmp/localstack:/tmp/localstack"
#      - "/var/run/docker.sock:/var/run/docker.sock"

  dynamodb:
    image: amazon/dynamodb-local
    hostname: dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8042:8000"

  postgres:
    container_name: image-library-postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=es
      - POSTGRES_PASSWORD=es
      - POSTGRES_DB=checkpoints
    ports:
      - 5432:5432