version: '3'

services:

  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    ports:
      - "8042:8000"

  sqs:
    image: roribio16/alpine-sqs
    ports:
      - 9324:9324
      - 9325:9325

  postgres:
    container_name: image-library-postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=es
      - POSTGRES_PASSWORD=es
      - POSTGRES_DB=checkpoints
    ports:
      - 5432:5432