version: '3'

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8042:8000"

  postgres:
    container_name: image-library-postgres
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=es
      - POSTGRES_PASSWORD=es
      - POSTGRES_DB=checkpoints
    ports:
      - 5432:5432