version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "443:443"
      - "4567-4599:4567-4599"
      - "8080:8080"
    environment:
      - LOCALSTACK_API_KEY=bSEhjitgiV
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/tmp/localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"