AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EventStoreTableName:
    Default: eventstore
    Description: Name of the eventstore table
    Type: String
  SequenceTableName:
    Default: sequences
    Description: Name of the eventstore table
    Type: String

Resources:

  SequenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref SequenceTableName
      AttributeDefinitions:
        - AttributeName: sequence
          AttributeType: S
      KeySchema:
        - AttributeName: sequence
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

  EventStoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref EventStoreTableName
      AttributeDefinitions:
        - AttributeName: streamId
          AttributeType: S
        - AttributeName: version
          AttributeType: N
        - AttributeName: position
          AttributeType: N
        - AttributeName: active
          AttributeType: N
        - AttributeName: committedAt
          AttributeType: N
      KeySchema:
        - AttributeName: streamId
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: active-committedAt-index
          KeySchema:
            - AttributeName: active
              KeyType: HASH
            - AttributeName: committedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: position
          KeySchema:
            - AttributeName: active
              KeyType: HASH
            - AttributeName: position
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE