AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  EventStoreTableName:
    Default: eventstore
    Description: Name of the eventstore table
    Type: String
  SequenceTableName:
    Default: sequences
    Description: Name of the eventstore table
    Type: String

Resources:

  EventStoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref EventStoreTableName
      AttributeDefinitions:
        - AttributeName: streamId
          AttributeType: S
        - AttributeName: version
          AttributeType: N
        - AttributeName: position
          AttributeType: N
        - AttributeName: active
          AttributeType: N
        - AttributeName: committedAt
          AttributeType: N
      KeySchema:
        - AttributeName: streamId
          KeyType: HASH
        - AttributeName: version
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: active-committedAt-index
          KeySchema:
            - AttributeName: active
              KeyType: HASH
            - AttributeName: committedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: active-position-index
          KeySchema:
            - AttributeName: active
              KeyType: HASH
            - AttributeName: position
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  ProjectionsQueue:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      FifoQueue: true

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ProjectionsQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub ${AWS::AccountId}
            Action:
              - sqs:SendMessage
            Resource:
              - !GetAtt ProjectionsQueue.Arn
