name: Build
on: [push]

env:
  LOCALSTACK_API_KEY: ${{ secrets.LOCALSTACK_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      localstack:
        image: localstack/localstack
        env:
          LOCALSTACK_API_KEY: ${{ env.LOCALSTACK_API_KEY }}
          DOCKER_HOST: unix:///var/run/docker.sock
        ports:
          - "4567-4599:4567-4599"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"

      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: es
          POSTGRES_PASSWORD: es
          POSTGRES_DB: checkpoints
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
      - name: build and test
        run: |
          make mod
          make build
          make test