name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta

      - name: docker-compose up
        run: docker-compose up -d

      - name: setup test resources
        run: |
          make create-local-tables
          make create-local-queues

      - name: build and test
        run: |
          make mod
          make build
          make test