name: Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta

      - name: setup test resources
        run: make setup

      - name: build and test
        run: |
          make mod
          make build
          make test